name: Node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.X]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Create Production Build For Cypress Test
        run: yarn build
      - name: Run Lint
        run: yarn lint
      - name: Run Jest Test
        run: yarn test
      - name: Run Cypress Test
        run: yarn cypress:test